# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Causal_movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Causales',
            },
        ),
        migrations.CreateModel(
            name='Centro_estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_liberacion', models.CharField(blank=True, max_length=500, null=True)),
                ('entidad_aceptacion', models.CharField(blank=True, max_length=500, null=True)),
                ('sintesis_causal_movimiento', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 8, 49, 838000))),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_aprobado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_DE_RE', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_DE_RS', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_aprobado', models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 8, 49, 843000))),
            ],
            options={
                'ordering': ['-fecha_aprobado'],
            },
        ),
        migrations.CreateModel(
            name='Expediente_no_aprobado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_no_aprobado', models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 8, 49, 844000))),
                ('sintesis_no_aprobado', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pendiente', models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 8, 49, 842000))),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_rechazado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_rechazo', models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 8, 49, 841000))),
                ('sintesis_rechazo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('siglas', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'img_usuarios/')),
                ('telefono', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Categoria_usuario')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('siglas', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expediente_movimiento_externo',
            fields=[
                ('expediente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SGMGU.Expediente')),
                ('facultado_liberacion', models.CharField(blank=True, max_length=250, null=True)),
                ('facultado_aceptacion', models.CharField(blank=True, max_length=250, null=True)),
                ('comprimido', models.FileField(blank=True, null=True, upload_to=b'doc_expedientes/')),
                ('organismo_aceptacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismo_aceptacion', to='SGMGU.Organismo')),
                ('organismo_liberacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismo_liberacion', to='SGMGU.Organismo')),
            ],
            bases=('SGMGU.expediente',),
        ),
        migrations.CreateModel(
            name='Expediente_movimiento_interno',
            fields=[
                ('expediente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SGMGU.Expediente')),
                ('aprobado_por', models.CharField(max_length=500)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
            ],
            bases=('SGMGU.expediente',),
        ),
        migrations.CreateModel(
            name='Facultado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SGMGU.Persona')),
                ('cargo', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
            ],
            bases=('SGMGU.persona',),
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SGMGU.Persona')),
                ('ci', models.CharField(blank=True, max_length=50, null=True)),
                ('anno_graduacion', models.IntegerField(max_length=4)),
                ('codigo_boleta', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen_boleta', models.ImageField(blank=True, null=True, upload_to=b'img_boletas/')),
                ('detalle_direccion_residencia', models.CharField(blank=True, max_length=500, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
                ('centro_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Centro_estudio')),
            ],
            bases=('SGMGU.persona',),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia'),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='causal_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Causal_movimiento'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='mun_entidad_aceptacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_aceptacion', to='SGMGU.Municipio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='mun_entidad_liberacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_liberacion', to='SGMGU.Municipio'),
        ),
        migrations.AddField(
            model_name='graduado',
            name='municipio_direccion_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AddField(
            model_name='graduado',
            name='provincia_direccion_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia'),
        ),
        migrations.AddField(
            model_name='expediente_rechazado',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Expediente_movimiento_externo'),
        ),
        migrations.AddField(
            model_name='expediente_pendiente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Expediente_movimiento_externo'),
        ),
        migrations.AddField(
            model_name='expediente_no_aprobado',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Expediente_movimiento_externo'),
        ),
        migrations.AddField(
            model_name='expediente_aprobado',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Expediente_movimiento_externo'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='graduado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Graduado', unique=True),
        ),
    ]
