# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0003_auto_20170216_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente_aprobado',
            name='carta_expediente',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/informe_expedientes_aprobados/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 33, 15, 442000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 33, 15, 447000)),
        ),
        migrations.AlterField(
            model_name='expediente_movimiento_externo',
            name='comprimido',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/doc_expedientes/'),
        ),
        migrations.AlterField(
            model_name='expediente_no_aprobado',
            name='fecha_no_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 33, 15, 448000)),
        ),
        migrations.AlterField(
            model_name='expediente_pendiente',
            name='fecha_pendiente',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 33, 15, 446000)),
        ),
        migrations.AlterField(
            model_name='expediente_rechazado',
            name='fecha_rechazo',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 33, 15, 445000)),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='anno_graduacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='imagen_boleta',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/img_boletas/'),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/img_usuarios/'),
        ),
    ]
