# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0004_auto_20170216_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 51, 26, 932000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='carta_expediente',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/cartas_expedientes/'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 51, 26, 937000)),
        ),
        migrations.AlterField(
            model_name='expediente_movimiento_externo',
            name='comprimido',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/adjuntos_expedientes/'),
        ),
        migrations.AlterField(
            model_name='expediente_no_aprobado',
            name='fecha_no_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 51, 26, 938000)),
        ),
        migrations.AlterField(
            model_name='expediente_pendiente',
            name='fecha_pendiente',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 51, 26, 936000)),
        ),
        migrations.AlterField(
            model_name='expediente_rechazado',
            name='fecha_rechazo',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 10, 51, 26, 935000)),
        ),
    ]
