# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0005_auto_20170216_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=256)),
                ('especialista', models.CharField(max_length=256)),
                ('correo_director', models.EmailField(max_length=254)),
                ('correo_especialista', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('provincia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia')),
            ],
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 10, 22, 32, 280000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 10, 22, 32, 285000)),
        ),
        migrations.AlterField(
            model_name='expediente_no_aprobado',
            name='fecha_no_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 10, 22, 32, 286000)),
        ),
        migrations.AlterField(
            model_name='expediente_pendiente',
            name='fecha_pendiente',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 10, 22, 32, 284000)),
        ),
        migrations.AlterField(
            model_name='expediente_rechazado',
            name='fecha_rechazo',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 10, 22, 32, 283000)),
        ),
    ]
