# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0012_auto_20170606_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 11, 37, 26, 555000)),
        ),
    ]
