# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:33
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0014_auto_20170607_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_graduado', models.IntegerField()),
                ('ci', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message=b'CI incorrecto', regex=b'^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')])),
                ('nombre_apellidos', models.CharField(max_length=256)),
                ('cumple_servicio_social', models.BooleanField()),
                ('entidad', models.CharField(max_length=256)),
                ('sexo', models.CharField(choices=[((b'M', b'Masculino'), (b'F', b'Femenino'))], max_length=1)),
                ('direccion_particular', models.CharField(max_length=256)),
                ('estado_ubicacion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
                ('centro_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Centro_estudio')),
                ('municipio_residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_residencia', to='SGMGU.Municipio')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
                ('provincia_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_ubicacion', to='SGMGU.Provincia')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 11, 33, 2, 285000)),
        ),
    ]
