# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0015_auto_20170615_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 11, 34, 20, 118000)),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='estado_ubicacion',
            field=models.CharField(choices=[(b'graduado', b'Graduado'), (b'pendiente_tesis', b'Pendiente de Tesis'), (b'desfasado', b'Desfasado')], max_length=20),
        ),
    ]
