# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0016_auto_20170615_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionlaboral',
            name='boleta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 12, 28, 54, 789000)),
        ),
    ]
