# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0019_auto_20170615_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_estudio',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 14, 47, 28, 358000)),
        ),
    ]
