# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0022_auto_20170628_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_trabajo',
            name='sexo_director',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 28, 12, 48, 51, 401000)),
        ),
    ]
