# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2008-04-30 06:45
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0024_auto_20080430_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadGraduados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_graduado', models.IntegerField()),
                ('ci', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message=b'CI incorrecto', regex=b'^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')])),
                ('nombre_apellidos', models.CharField(max_length=256)),
                ('sexo', models.CharField(max_length=20)),
                ('direccion_particular', models.CharField(max_length=256)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
                ('centro_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Centro_estudio')),
                ('municipio_residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad_municipio_residencia', to='SGMGU.Municipio')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2008, 4, 30, 2, 45, 44, 468000)),
        ),
    ]
