# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 16:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0026_auto_20080430_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionlaboral',
            name='estado_ubicacion',
        ),
        migrations.AddField(
            model_name='carrera',
            name='codigo_mes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centro_estudio',
            name='codigo_mes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_mes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 12, 2, 8, 123000)),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='boleta',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message=b'CI incorrecto', regex=b'^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='municipio_residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_municipio_residencia', to='SGMGU.Municipio'),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='provincia_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_provincia_ubicacion', to='SGMGU.Provincia'),
        ),
    ]
