# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0028_auto_20170629_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_estudio',
            name='siglas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 16, 2, 33, 829000)),
        ),
    ]
