# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0029_auto_20170629_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionlaboral',
            name='causa_no_presentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 16, 10, 3, 809000)),
        ),
    ]
