# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0030_auto_20170630_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 16, 11, 7, 627000)),
        ),
        migrations.AlterField(
            model_name='ubicacionlaboral',
            name='presentado',
            field=models.BooleanField(default=True),
        ),
    ]
