# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0033_auto_20080430_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadgraduados',
            name='cumple_servicio_social',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 13, 7, 52, 542000)),
        ),
    ]
