# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0034_auto_20170703_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionlaboral',
            name='estado_ubicacion',
            field=models.CharField(choices=[(b'desfasado', b'Desfasado'), (b'graduado', b'Graduado')], default='graduado', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 11, 4, 32, 126000)),
        ),
    ]
