# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 17:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0036_auto_20170717_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduadoInhabilitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.IntegerField()),
                ('nombre_apellidos', models.CharField(max_length=256)),
                ('ci', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message=b'CI incorrecto', regex=b'^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')])),
                ('nivel_educacional', models.CharField(choices=[(b'Superior', b'NS'), (b'Medio', b'NM')], max_length=90)),
                ('cumple_servicio_social', models.CharField(choices=[(b'Si', b'C'), (b'No', b'NC')], max_length=90)),
                ('causal_incumplimiento', models.CharField(choices=[(b'sp', b'Salida del pa\xc3\xads'), (b'd', b'Desmotivaci\xc3\xb3n'), (b'pp', b'Problemas Personales'), (b'eol', b'Ejerce otra labor'), (b'h', b'Habilitaci\xc3\xb3n'), (b'o', b'Otras')], max_length=90)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Provincia')),
            ],
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 13, 28, 53, 710000)),
        ),
    ]
