# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0037_auto_20170802_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduadoinhabilitacion',
            name='numero_resolucion',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 14, 55, 30, 117000)),
        ),
    ]
