# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0041_auto_20170802_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhabilitacion',
            name='causal_incumplimiento',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='causal_incumplimiento',
        ),
        migrations.AddField(
            model_name='inhabilitacion',
            name='causal',
            field=models.CharField(choices=[(b'h', b'Habilitaci\xc3\xb3n'), (b'sp', b'Salida del pa\xc3\xads'), (b'd', b'Desmotivaci\xc3\xb3n'), (b'pp', b'Problemas Personales'), (b'eol', b'Ejerce otra labor'), (b'o', b'Otras')], default='1', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspension',
            name='causal',
            field=models.CharField(choices=[(b'h', b'Habilitaci\xc3\xb3n'), (b'sp', b'Salida del pa\xc3\xads'), (b'd', b'Desmotivaci\xc3\xb3n'), (b'pp', b'Problemas Personales'), (b'eol', b'Ejerce otra labor'), (b'o', b'Otras')], default='1', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 16, 19, 33, 168000)),
        ),
    ]
