# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0042_auto_20170802_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoInhabilitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('causal', models.CharField(choices=[(b'h', b'Habilitaci\xc3\xb3n'), (b'sp', b'Salida del pa\xc3\xads'), (b'd', b'Desmotivaci\xc3\xb3n'), (b'pp', b'Problemas Personales'), (b'eol', b'Ejerce otra labor'), (b'o', b'Otras')], max_length=90)),
                ('proceso', models.CharField(choices=[(b's', b'Suspensi\xc3\xb3n'), (b'i', b'Inhabilitaci\xc3\xb3n')], max_length=90)),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.GraduadoInhabilitacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='inhabilitacion',
            name='graduado',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='graduado',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 9, 48, 16, 111000)),
        ),
        migrations.DeleteModel(
            name='Inhabilitacion',
        ),
        migrations.DeleteModel(
            name='Suspension',
        ),
    ]
