# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0043_auto_20170803_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduadoinhabilitacion',
            old_name='fecha_registro',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 15, 54, 48, 902000)),
        ),
    ]
