# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0046_auto_20170804_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduadoinhabilitacion',
            old_name='fecha',
            new_name='fecha_registrado',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 16, 2, 16, 69000)),
        ),
    ]
