# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2008-04-30 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0048_auto_20080430_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='causal_movimiento',
            name='tipo',
            field=models.CharField(choices=[(b'ml', b'Movimiento LaboraL'), (b'i', b'Inhabilitaci\xc3\xb3n')], default='M', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2008, 4, 30, 1, 59, 20, 421000)),
        ),
    ]
