# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2008-04-30 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0049_auto_20080430_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2008, 4, 30, 2, 0, 34, 390000)),
        ),
    ]
