# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2008-04-30 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0050_auto_20080430_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causal_movimiento',
            name='tipo',
            field=models.CharField(choices=[(b'ml', b'Movimiento Laboral'), (b'i', b'Inhabilitaci\xc3\xb3n')], max_length=90),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2008, 4, 30, 2, 15, 3, 937000)),
        ),
        migrations.AlterField(
            model_name='procesoinhabilitacion',
            name='causal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Causal_movimiento'),
        ),
    ]
