# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0051_auto_20080430_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 9, 49, 9, 208000)),
        ),
        migrations.AlterField(
            model_name='procesoinhabilitacion',
            name='proceso',
            field=models.CharField(choices=[(b'i', b'Inhabilitaci\xc3\xb3n'), (b's', b'Suspensi\xc3\xb3n')], max_length=90),
        ),
    ]
