# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0052_auto_20170807_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 9, 54, 35, 131000)),
        ),
    ]
