# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0053_auto_20170807_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[(b'nm', b'Nivel Medio'), (b'ns', b'Nivel Superior')], default='ns', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 10, 57, 53, 974000)),
        ),
    ]
