# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0054_auto_20170807_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 15, 22, 56, 174000)),
        ),
        migrations.AlterField(
            model_name='procesoinhabilitacion',
            name='numero_resolucion',
            field=models.IntegerField(unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='procesoinhabilitacion',
            name='proceso',
            field=models.CharField(choices=[(b'i', b'Inhabilitaci\xc3\xb3n'), (b's', b'Suspensi\xc3\xb3n de la Inhabilitaci\xc3\xb3n')], max_length=90),
        ),
    ]
