# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0057_auto_20170807_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaGraduados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_demanda', models.CharField(max_length=255, unique=True)),
                ('nombre_entidad', models.CharField(max_length=255, unique=True)),
                ('codigo_carrera', models.CharField(max_length=255)),
                ('anno_realizacion', models.IntegerField()),
                ('anno_mas_uno', models.IntegerField()),
                ('anno_mas_dos', models.IntegerField()),
                ('anno_mas_tres', models.IntegerField()),
                ('anno_mas_cuatro', models.IntegerField()),
                ('anno_mas_cinco', models.IntegerField()),
                ('anno_mas_seis', models.IntegerField()),
                ('anno_mas_siete', models.IntegerField()),
                ('anno_mas_ocho', models.IntegerField()),
                ('anno_mas_nueve', models.IntegerField()),
                ('anno_mas_diez', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('municipio_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 12, 3, 55, 91000)),
        ),
    ]
