# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0060_auto_20170809_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandagraduados',
            name='municipio_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 15, 41, 27, 802000)),
        ),
    ]
