# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0063_auto_20170809_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandagraduados',
            old_name='municipio_entidad',
            new_name='codigo_municipio_entidad',
        ),
        migrations.AddField(
            model_name='demandagraduados',
            name='codigo_organismo',
            field=models.CharField(default='1022000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 12, 26, 35, 979000)),
        ),
    ]
