# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 13:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGMGU', '0064_auto_20170810_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIndicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('texto', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fichero', models.FileField(blank=True, null=True, upload_to=b'uploads/archivos_indicaciones/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CategoriaIndicacion')),
            ],
            options={
                'ordering': ['-fecha_registro'],
                'verbose_name': 'Indicacion',
                'verbose_name_plural': 'Indicaciones',
            },
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 9, 42, 1, 33000)),
        ),
    ]
