# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0065_auto_20170828_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandaGraduados',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 7, 11, 55, 1, 120000)),
        ),
    ]
